function createfigure_stable(X1, Y1, YMatrix1)
%CREATEFIGURE1(X1, Y1, YMatrix1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-Oct-2020 10:04:21

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'DisplayName','S','Parent',subplot1);

% Create ylabel
ylabel({'Population size'});

% Create xlabel
xlabel({'time (days)'});

% Create title
title({'System Dynamics (R = 0.75)'});

box(subplot1,'on');
grid(subplot1,'on');
% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot2);
set(plot1(1),'DisplayName','Q');
set(plot1(2),'DisplayName','E');
set(plot1(3),'DisplayName','I');
set(plot1(4),'DisplayName','R');

% Create ylabel
ylabel({'Population size'});

% Create xlabel
xlabel({'time (days)'});

box(subplot2,'on');
grid(subplot2,'on');
% Create legend
legend(subplot2,'show');

