function createfigure_unstable(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 29-Oct-2020 09:38:49

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','S');
set(plot1(2),'DisplayName','R');

% Create ylabel
ylabel({'Population size'});

% Create xlabel
xlabel({'time (days)'});

% Create title
title({'System dynamics (R_0=1.83)'});

box(subplot1,'on');
grid(subplot1,'on');
% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','Q');
set(plot2(2),'DisplayName','E');
set(plot2(3),'DisplayName','I');

% Create ylabel
ylabel({'Population size'});

% Create xlabel
xlabel({'time(days)'});

% Create title
title({''});

box(subplot2,'on');
grid(subplot2,'on');
% Create legend
legend(subplot2,'show');

