function createfigure4(X1, YMatrix1, YMatrix2, Y1)
%CREATEFIGURE(X1, YMatrix1, YMatrix2, Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-Jan-2021 10:41:32

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',1);
set(plot1(1),'DisplayName','total tests');
set(plot1(2),'DisplayName','positive results');

% Create title
title({'Epidemiological Situation in Cantabria'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-292.807367614333 3397.28884705469]);
box(subplot1,'on');
grid(subplot1,'on');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.143204955096354 0.863585337223987 0.177954843992573 0.0523349422955475]);

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',1);
set(plot2(1),'DisplayName','hospitalized');
set(plot2(2),'DisplayName','ICU');
set(plot2(3),'DisplayName','deaths');

% Create ylabel
ylabel({'# people'});

% Create title
title({''});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-64.6604465086066 422.548508715274]);
box(subplot2,'on');
grid(subplot2,'on');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,...
    'Position',[0.741478535547713 0.539108695314333 0.154050462234859 0.07568437801659]);

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y1,'DisplayName','recovered','Parent',subplot3,'LineWidth',1);

% Create ylabel
ylabel({'#people'});

% Create xlabel
xlabel({'time (day)'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-49.7462696815606 518.619401960231]);
box(subplot3,'on');
grid(subplot3,'on');
% Create legend
legend3 = legend(subplot3,'show');
set(legend3,...
    'Position',[0.161797259923685 0.270187586130474 0.140770250147241 0.0289855065745048]);
saveas(figure1, "figure4_CB.png");
saveas(figure1, "figure4_CB", "epsc");

