function createfigure3(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Jan-2021 15:23:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','hospitalized');
set(plot1(2),'DisplayName','ICU');
set(plot1(3),'DisplayName','deaths');

% Create ylabel
ylabel({''});

% Create xlabel
xlabel({'date'});

% Create title
title({'Hospitalized, ICU and Deaths per day in Cantabria'});

box(axes1,'on');
grid(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.646198834226145 0.723538707759332 0.217543855832334 0.118483409144302]);

saveas(figure1, "figure3_CB.png");
saveas(figure1, "figure3_CB", "epsc");