function createfigure1(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 08-Jan-2021 15:26:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1);

% Create ylabel
ylabel({'number of positive test results'});

% Create xlabel
xlabel({'date'});

% Create title
title({'Number of Covid-19 Positive Test Results in Cantabria'});

box(axes1,'on');
grid(axes1,'on');
saveas(figure1, "figure1_CB.png");
saveas(figure1, "figure1_CB", "epsc");
