function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Jan-2021 11:30:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','hospitalized');
set(plot1(2),'DisplayName','UCI');
set(plot1(3),'DisplayName','deaths');

% Create ylabel
ylabel({''});

% Create xlabel
xlabel({'date'});

% Create title
title({'Number of Hospiralizations, UCI and Deaths per day ','in Basque Country'});

box(axes1,'on');
grid(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.548861740534984 0.692507337872973 0.221428567543626 0.119047615854513]);
saveas(figure1, "figure6_PV.png");
saveas(figure1, "figure6_PV", "epsc");

