function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 07-Jan-2021 12:52:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'Marker','*');

% Create ylabel
ylabel({'number of deaths'});

% Create xlabel
xlabel({'date'});

% Create title
title({'Cumulative Number of Death in Basque Country'});

grid(axes1,'on');

