function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 07-Jan-2021 12:50:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1);

% Create ylabel
ylabel({'number of hospitalized people'});

% Create xlabel
xlabel({'date'});

% Create title
title({'Hospitalized People in the Basque Country'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[197.093023255814 697.093023255814]);
box(axes1,'on');
grid(axes1,'on');
