function createfigure4(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 23-Jan-2021 11:09:34

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',1);
set(plot1(1),'DisplayName','total tests');
set(plot1(2),'DisplayName','positive results');

% Create title
title({'Epidemiological Situation in Castile and Leon'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-1795.58010645071 25552.4861918918]);
box(subplot1,'on');
grid(subplot1,'on');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.171850379558204 0.834702399639766 0.198561147348486 0.0613207531425188]);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',subplot2,'LineWidth',1);
set(plot2(1),'DisplayName','hospitalized');
set(plot2(2),'DisplayName','ICU');
set(plot2(3),'DisplayName','deaths');

% Create ylabel
ylabel({'# people'});

% Create xlabel
xlabel({'time (day)'});

% Create title
title({''});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-296.9612994115 2437.84533042275]);
box(subplot2,'on');
grid(subplot2,'on');
% Create legend
legend(subplot2,'show');

