function createfigure2(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 09-Jan-2021 19:29:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1);

% Create ylabel
ylabel({'number of positives/number of tests'});

% Create xlabel
xlabel({'date'});

% Create title
title({'Covid-19 Test Positivity in Castile and Leon'});

box(axes1,'on');
grid(axes1,'on');
saveas(figure1, "figure2_CL.png");
saveas(figure1, "figure2_CL", "epsc");
