function createfigure3(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Jan-2021 19:34:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','hospitalized');
set(plot1(2),'DisplayName','UCI');
set(plot1(3),'DisplayName','deaths');

% Create ylabel
ylabel({''});

% Create xlabel
xlabel({'date'});

% Create title
title({'Number of Hospitalizations, UCI and Deaths per day ','in Castile and Leon'});

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'LineWidth',1);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.630952383826176 0.767460320653424 0.221428567543626 0.119047615854513]);

saveas(figure1, "figure3_CL.png");
saveas(figure1, "figure3_CL", "epsc");

