function [fitresult, gof] = createFit2dp(Q, dp)
%CREATEFIT(Q,DP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Q
%      Y Output: dp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Mar-2021 15:06:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Q, dp );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = excludedata( xData, yData, 'Indices', [170 171 172 173 174 175 176 177 178 179 180 181 182 183 186 188] );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'dp vs. Q', 'Excluded dp vs. Q', 'y = 7,1E-4x', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Q', 'Interpreter', 'none' );
ylabel( 'dp', 'Interpreter', 'none' );
grid on


