function [fitresult, gof] = createFit2r(Q, r)
%CREATEFIT(Q,R)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Q
%      Y Output: r
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Mar-2021 15:02:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Q, r );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = excludedata( xData, yData, 'Indices', [73 74 75 76 77 95 97 98 99 100 102 103 104 159 160] );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'r vs. Q', 'Excluded r vs. Q', 'y = 0.043x+11', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Q', 'Interpreter', 'none' );
ylabel( 'r', 'Interpreter', 'none' );
grid on


